[project]
name = "toolkit"
version = "0.1.0"
description = "Shared utilities for Python projects"
readme = "README.md"
authors = [
    { name = "Octavian Tocan", email = "tocanoctavian@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "ollama-service",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/toolkit"]

[tool.hatch.build.targets.sdist]
include = ["src/toolkit"]

[tool.uv.workspace]
members = [
    "ollama-service",
]

[tool.uv.sources]
ollama-service = { workspace = true, editable = true }

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]
